# Basic
title: 詹明捷的博客
subtitle: “大圣，此去欲何？” “踏南天，碎凌霄” “如若一去不回……？” “便一去不回！”
welcome_message: <a  target="_blank">关于计算机视觉</a>
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 欢迎访问
creator: <a href="http://zhanmingjie.com">@zhanmingjie</a>

url: "http://zhanmingjie.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    #- {title: Projects, description: My Projects, url: 'http://zhanmingjie.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: zhanmingjie
    # duoshuo: 
    
# Social
social:
    #weibo: 
    #github: 
    #twitter: 
    #gplus: 
    mail: zmjdll@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
    
---
layout: default
comments: true
# other options
---

markdown:    kramdown
